-- 产品主数据 sku(从 ERP 复制的基础字段)。
-- 远程 EU 库已有此表与数据,这里用 IF NOT EXISTS / INSERT OR IGNORE 保证幂等;
-- 本地开发库(miniflare)会据此建表并灌入种子数据。
CREATE TABLE IF NOT EXISTS sku (
  id         INTEGER PRIMARY KEY,
  code       TEXT NOT NULL UNIQUE,
  name       TEXT NOT NULL,
  name_zh    TEXT,
  category   TEXT,
  color      TEXT,
  series     TEXT,
  family     TEXT,
  lifecycle  TEXT NOT NULL DEFAULT 'active',
  is_active  INTEGER NOT NULL DEFAULT 1,
  sort_order INTEGER NOT NULL DEFAULT 0
);

INSERT OR IGNORE INTO sku (id, code, name, name_zh, category, color, series, family, lifecycle, is_active, sort_order) VALUES
(1,'C21-P1','Leopard Magnetic Cable 100W',NULL,'Cable',NULL,'Leopard','Leopard','active',1,10),
(2,'C22-P1','Leopard Magnetic Cable 240W',NULL,'Cable',NULL,'Leopard','Leopard','active',1,20),
(3,'C11-P1-Black','Leopard Cable 100W-Black',NULL,'Cable','Black','Leopard','Leopard','active',1,30),
(4,'C11-P1-Orange','Leopard Cable 100W - Orange',NULL,'Cable','Orange','Leopard','Leopard','active',1,31),
(5,'C11-P1-Blue','Leopard Cable 100W - Blue',NULL,'Cable','Blue','Leopard','Leopard','active',1,32),
(6,'CD11','Display Cable 100W',NULL,'Cable',NULL,'Cable','Display Cable','active',1,40),
(7,'CD21','Display Cable 240W',NULL,'Cable',NULL,'Cable','Display Cable','active',1,50),
(8,'P41L-P1','PowerPaw 10K',NULL,'Power bank',NULL,'Other','Pocket Other','active',1,100),
(9,'P61L-P1','Pocket 10K',NULL,'Power bank',NULL,'Pocket','Pocket','active',1,110),
(10,'P61L-P2','Pocket 10K 45W',NULL,'Power bank',NULL,'Pocket','Pocket','npi',1,120),
(11,'P51L-P2','Pocket 20K 45W',NULL,'Power bank',NULL,'Pocket','Pocket','npi',1,130),
(12,'P62-P1','Leopard Power 65W',NULL,'Power bank',NULL,'Leopard','Leopard Power','active',1,200),
(13,'P63-P1','Leopard Power 100W',NULL,'Power bank',NULL,'Leopard','Leopard Power','active',1,210),
(14,'P64-P1','Leopard Power 140W',NULL,'Power bank',NULL,'Leopard','Leopard Power','active',1,220),
(15,'P75-P1-Black','MagPro Slim 5K - Black',NULL,'Power bank','Black','MagPro','MagPro Slim','active',1,300),
(16,'P75-P1-White','MagPro Slim 5K - White',NULL,'Power bank','White','MagPro','MagPro Slim','active',1,301),
(17,'P75-P1-Titan','MagPro Slim 5K - Titan',NULL,'Power bank','Titan','MagPro','MagPro Slim','active',1,302),
(18,'P75-P1-DesertTitan','MagPro Slim 5K - Desert Titan',NULL,'Power bank','Desert Titan','MagPro','MagPro Slim','active',1,303),
(19,'P75-P1-Orange','MagPro Slim 5K - Orange',NULL,'Power bank','Orange','MagPro','MagPro Slim','active',1,304),
(20,'P75-P1-Blue','MagPro Slim 5K - Blue',NULL,'Power bank','Blue','MagPro','MagPro Slim','active',1,305),
(21,'P76-P1-Black','MagPro Slim 10K - Black',NULL,'Power bank','Black','MagPro','MagPro Slim','active',1,320),
(22,'P76-P1-White','MagPro Slim 10K - White',NULL,'Power bank','White','MagPro','MagPro Slim','active',1,321),
(23,'P76-P1-Titan','MagPro Slim 10K - Titan',NULL,'Power bank','Titan','MagPro','MagPro Slim','active',1,322),
(24,'PPT01-Black','Pocket Pro 10K 45W-Black',NULL,'Power bank','Black','Pocket','Pocket Pro','active',1,400),
(25,'PPT51','Pocket Pro 10K 45W Slim',NULL,'Power bank',NULL,'Pocket','Pocket Pro','eol',1,410),
(26,'PM61-Orange','MagPro Slim 10K Qi2.2 - Orange',NULL,'Power bank','Orange','MagPro','MagPro Slim','npi',1,500),
(27,'PM61-Blue','MagPro Slim 10K Qi2.2 - Blue',NULL,'Power bank','Blue','MagPro','MagPro Slim','npi',1,501),
(28,'PM61-Black','MagPro Slim 10K Qi2.2 - Black',NULL,'Power bank','Black','MagPro','MagPro Slim','npi',1,502),
(29,'PM61-White','MagPro Slim 10K Qi2.2 - White',NULL,'Power bank','White','MagPro','MagPro Slim','npi',1,503),
(30,'PX11','Pocket Neo 10K',NULL,'Power bank',NULL,'Pocket','Pocket Neo','active',1,600),
(31,'PX21','Pocket Neo 20K',NULL,'Power bank',NULL,'Pocket','Pocket Neo','active',1,610),
(32,'PX51','MagPro Neo 10K Qi2.0',NULL,'Power bank',NULL,'MagPro','MagPro Neo','npi',1,620),
(33,'PX41-Black','MagPro Neo 5K Qi2.0 - Black',NULL,'Power bank','Black','MagPro','MagPro Neo','npi',1,621),
(34,'PX41-White','MagPro Neo 5K Qi2.0 - White',NULL,'Power bank','White','MagPro','MagPro Neo','npi',1,622),
(36,'WM211','MagPro Stand',NULL,'Wireless charger',NULL,'MagPro','MagPro','active',1,710),
(37,'TAL101','Omni Charging Station 130W',NULL,'Charger',NULL,'Omni','Omni','active',1,720),
(38,'WAL11','Leopard Fold Charger 70W - EU',NULL,'Charger',NULL,'Leopard','Leopard','active',1,800),
(39,'WAL101','Leopard Fold Charger 100W - EU',NULL,'Charger',NULL,'Leopard','Leopard','active',1,810),
(40,'WAL21','Leopard Smart Charger 70W',NULL,'Charger',NULL,'Leopard','Leopard','active',1,820),
(41,'WAL131','Leopard Smart Charger 100W',NULL,'Charger',NULL,'Leopard','Leopard','active',1,830),
(42,'Bundle 1','Leopard Fold Charger 100W + Cable 100W 2m + Cable 240W 2m',NULL,'Bundle',NULL,NULL,NULL,'active',1,900),
(43,'Bundle 2','Leopard Cable 100W 1m + Cable 100W 2m + Cable 240W 2m',NULL,'Bundle',NULL,NULL,NULL,'active',1,910),
(44,'C12-P1-Black','Leopard Cable 240W-Black',NULL,'Cable',NULL,'Leopard','Leopard','active',1,0),
(45,'P51L-P1','Pocket 20K',NULL,'Power bank',NULL,'Pocket','Pocket','active',1,0),
(46,'P72-P1','MagPro 10K',NULL,'Power bank',NULL,'MagPro','MagPro Other','active',1,0),
(49,'PM141','Pocket Plus 10K Watch',NULL,'Power bank',NULL,'Pocket','Pocket Plus','active',1,0),
(52,'PPT11','Pocket Pro 20K 45W',NULL,'Power bank',NULL,'Pocket','Pocket Pro','active',1,0),
(54,'TAL11','Omni Charging Station 300W',NULL,'Charger',NULL,'Omni','Omni','active',1,0),
(55,'WAL45','Wall Charger 45W',NULL,'Charger',NULL,'Leopard','Leopard','active',1,0),
(57,'WM311-Black','MagPro 3-in-1 - Black',NULL,'Wireless charger','Black','MagPro','MagPro','active',1,0),
(58,'WM311-White','MagPro 3-in-1 - White',NULL,'Wireless charger','White','MagPro','MagPro','active',1,0),
(59,'WM321','MagPro 3-in-1 Station',NULL,'Wireless charger',NULL,'MagPro','MagPro','active',1,0),
(60,'P75-P1-Red','MagPro Slim 5K-Red',NULL,'Power bank','Red','MagPro','MagPro Slim','active',1,999),
(61,'P75-P1-LB','MagPro Slim 5K-Light Blue',NULL,'Power bank','Light Blue','MagPro','MagPro Slim','active',1,999),
(62,'PPT01-White','Pocket Pro 10K 45W',NULL,'Power bank','White','Pocket','Pocket Pro','active',1,999),
(63,'WM301-Black','MagPro 2-in-1-Black',NULL,'Wireless charger','Black','MagPro','MagPro','active',1,999),
(64,'PA51','Rugged 20K',NULL,'Power bank','Blue','Rugged','Rugged','active',1,999),
(66,'WM301-White','MagPro 2-in-1 -White',NULL,'Wireless charger','White','MagPro','MagPro','active',1,999),
(67,'WAX31','Leopard Charger 45W',NULL,'Charger',NULL,'Leopard','Leopard','active',1,999),
(68,'VL11','Car Charger',NULL,'Charger',NULL,'Car Charger','Car Charger','active',1,999),
(75,'UFO-White','UFO 3-in-1 - White',NULL,'Wireless charger','White','UFO','UFO','npi',1,999),
(76,'UFO-Red','UFO 3-in-1 - Red',NULL,'Wireless charger','Red','UFO','UFO','npi',1,999),
(78,'UFO-LB','UFO 3-in-1 - Light Blue',NULL,'Wireless charger','Light Blue','UFO','UFO','npi',1,999),
(80,'PM61-Titan','MagPro Slim 10K Qi2.2 - Titan',NULL,'Power bank','Titan','MagPro','MagPro Slim','npi',1,999),
(81,'C12-P1-Red','Leopard Cable 240W - Red',NULL,'Cable','Red','Leopard','Leopard','active',1,999),
(82,'C11-P1-Red','Leopard Cable 100W - Red',NULL,'Cable','Red','Leopard','Leopard','active',1,999),
(83,'C11-P1-LB','Leopard Cable 100W - LB',NULL,'Cable','Light Blue','Leopard','Leopard','active',1,999);
